
services:
  snmp-service:
    build: ./snmp-service
    container_name: snmp-service
    restart: always
    env_file:
      - ./snmp-service/.env
    networks:
      - ups-net

  
  telegram-bot:
    build: ./telegram
    container_name: telegram-ups
    restart: always
    env_file:
      - ./telegram/.env
    depends_on:
      - snmp-service
    networks:
      - ups-net

networks:
  ups-net:
    driver: bridge
